{
 "title": "ODyS-TIG - MONC",
 "description": "DynamicScaling - Measure of OCPU/ECPU, Node and Cluster Load",
 "tags": [
  "influxdb",
  "dynamicscaling"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "🔳 OCPU & 🖥 Node Load Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OCPU/ECPU and Node Load Overview",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Current OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Current OCPU/ECPU\"})\n  |> yield(name: \"Current OCPU/ECPU\")"
    },
    {
     "alias": "Node Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_nload.csv\")\n  |> filter(fn: (r) => r._field == \"Node Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Node Load\"})\n  |> yield(name: \"Node Load\")"
    }
   ]
  },
  {
   "title": "🔳 Current OCPU/ECPU Utilization (Current and 2h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Current OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Current OCPU/ECPU\"})\n  |> yield(name: \"Current OCPU/ECPU\")"
    },
    {
     "alias": "2h Avg OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: 2h, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"2h Avg OCPU/ECPU\"})\n  |> yield(name: \"(2h) Avg OCPU\")"
    }
   ]
  },
  {
   "title": "🖥 Node Load (Current and 2h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Node Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_nload.csv\")\n  |> filter(fn: (r) => r._field == \"Node Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Node Load\"})\n  |> yield(name: \"Node Load\")"
    },
    {
     "alias": "2h Avg Node Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_nload.csv\")\n  |> filter(fn: (r) => r._field == \"Node Load\")\n  |> aggregateWindow(every: 2h, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"2h Avg Node Load\"})\n  |> yield(name: \"(2h) Avg Node Load\")"
    }
   ]
  },
  {
   "title": "🔳 OCPU & 🌐 Cluster Load Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "OCPU/ECPU and Cluster Load Overview",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Current OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Current OCPU/ECPU\"})\n  |> yield(name: \"Current OCPU/ECPU\")"
    },
    {
     "alias": "Cluster Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_cload.csv\")\n  |> filter(fn: (r) => r._field == \"Cluster Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Cluster Load\"})\n  |> yield(name: \"Cluster Load\")"
    }
   ]
  },
  {
   "title": "🔳 Current OCPU/ECPU Utilization (Current and 2h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Current OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Current OCPU/ECPU\"})\n  |> yield(name: \"Current OCPU/ECPU\")"
    },
    {
     "alias": "2h Avg OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: 2h, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"2h Avg OCPU/ECPU\"})\n  |> yield(name: \"(2h) Avg OCPU\")"
    }
   ]
  },
  {
   "title": "🌐 Cluster Load (Current and 2h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Cluster Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_cload.csv\")\n  |> filter(fn: (r) => r._field == \"Cluster Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Cluster Load\"})\n  |> yield(name: \"Cluster Load\")"
    },
    {
     "alias": "2h Avg Cluster Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_cload.csv\")\n  |> filter(fn: (r) => r._field == \"Cluster Load\")\n  |> aggregateWindow(every: 2h, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"2h Avg Cluster Load\"})\n  |> yield(name: \"(2h) Avg Cluster Load\")"
    }
   ]
  },
  {
   "title": "⚙️ Comprehensive Analysis (OCPU/ECPU - Node - Cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "OCPU/ECPU, Cluster Load, and Node Load Combined View",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Current OCPU/ECPU",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_ocpu.csv\")\n  |> filter(fn: (r) => r._field == \"Current OCPU/ECPU\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Current OCPU/ECPU\"})\n  |> yield(name: \"Current OCPU/ECPU\")"
    },
    {
     "alias": "Cluster Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_cload.csv\")\n  |> filter(fn: (r) => r._field == \"Cluster Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Cluster Load\"})\n  |> yield(name: \"Cluster Load\")"
    },
    {
     "alias": "Node Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_nload.csv\")\n  |> filter(fn: (r) => r._field == \"Node Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Node Load\"})\n  |> yield(name: \"Node Load\")"
    }
   ]
  },
  {
   "title": "🌐 Cluster Load (Current and 2h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Cluster Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_cload.csv\")\n  |> filter(fn: (r) => r._field == \"Cluster Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Cluster Load\"})\n  |> yield(name: \"Cluster Load\")"
    },
    {
     "alias": "2h Avg Cluster Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_cload.csv\")\n  |> filter(fn: (r) => r._field == \"Cluster Load\")\n  |> aggregateWindow(every: 2h, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"2h Avg Cluster Load\"})\n  |> yield(name: \"(2h) Avg Cluster Load\")"
    }
   ]
  },
  {
   "title": "🖥 Node Load (Current and 2h Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Node Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_nload.csv\")\n  |> filter(fn: (r) => r._field == \"Node Load\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"Node Load\"})\n  |> yield(name: \"Node Load\")"
    },
    {
     "alias": "2h Avg Node Load",
     "query": "from(bucket: \"dynamicscaling\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"directory_monitor\" and r.filename == \"dynamicscaling-chart_nload.csv\")\n  |> filter(fn: (r) => r._field == \"Node Load\")\n  |> aggregateWindow(every: 2h, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"2h Avg Node Load\"})\n  |> yield(name: \"(2h) Avg Node Load\")"
    }
   ]
  }
 ]
}